version: '3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=task_4bill.py
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data: